In [ ]:
import pandas as pd
import numpy as np
import re
import string
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
data=pd.read_csv("Reviews.csv")
data

Id   ProductId          UserId                      ProfileName  \
0            1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1            2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2            3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3            4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4            5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
...        ...         ...             ...                              ...   
568449  568450  B001EO7N10  A28KG5XORO54AY                 Lettie D. Carter   
568450  568451  B003S1WTCU  A3I8AFVPEE8KI5                        R. Sawyer   
568451  568452  B004I613EE  A121AA1GQV751Z                    pksd "pk_007"   
568452  568453  B004I613EE   A3IBEVCTXKNOH          Kathy A. Welch "katwel"   
568453  568454  B001LR2CU2  A3LGQPJCZVL9UC                         srfell17   

        HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                          1                       1      5  1303862400   
1                          0                       0      1  1346976000   
2                          1                       1      4  1219017600   
3                          3                       3      2  1307923200   
4                          0                       0      5  1350777600   
...                      ...                     ...    ...         ...   
568449                     0                       0      5  1299628800   
568450                     0                       0      2  1331251200   
568451                     2                       2      5  1329782400   
568452                     1                       1      5  1331596800   
568453                     0                       0      5  1338422400   

                                   Summary  \
0                    Good Quality Dog Food   
1                        Not as Advertised   
2                    "Delight" says it all   
3                           Cough Medicine   
4                              Great taffy   
...                                    ...   
568449                 Will not do without   
568450                        disappointed   
568451            Perfect for our maltipoo   
568452  Favorite Training and reward treat   
568453                         Great Honey   

                                                     Text  
0       I have bought several of the Vitality canned d...  
1       Product arrived labeled as Jumbo Salted Peanut...  
2       This is a confection that has been around a fe...  
3       If you are looking for the secret ingredient i...  
4       Great taffy at a great price.  There was a wid...  
...                                                   ...  
568449  Great for sesame chicken..this is a good if no...  
568450  I'm disappointed with the flavor. The chocolat...  
568451  These stars are small, so you can give 10-15 o...  
568452  These are the BEST treats for training and rew...  
568453  I am very satisfied ,product is as advertised,...  

[568454 rows x 10 columns]

In [ ]:
df=data

In [ ]:
unique_scores = df['Score'].unique()
print(unique_scores)


[5 1 4 2 3]


In [ ]:
unique = df['HelpfulnessDenominator'].unique()
print(unique)

[  1   0   3   4   2   5  19  13   9   7  15   8   6  10  47  17  14  27
  12  11  21  31  18  23 168  46  30 133  16  36  25  26  24  22  29  20
  64 216  33 112 108  51  37  39  89  35  43  42  74  49  34  28  53  96
  58  41  65 130 100  84  38  40  32  48 219 155  83  85  72  56  63 128
  79  76  55  68  66  44  94  59 117 188 134  92  57  71  98  90  45 135
 170  77  52 123  50  93  88 122 212 192 120 401 209  95  86  99  73  60
 124  54  61  70 180  91  81 138 163 307 270 151  78  62 119 139 137 215
 539 305 562 477 235  87  69 298  75  82 103 156 110 144  80  67 127 162
 181 356 245 462 174 111 182 143 179 159 101 171  97 249 384 187 121 263
 131 165 416 106 878 536 238 109 923 115 150 371 105 154 125 149 569 360
 222 593 185 486 126 114 140 452 323 365 197 284 488 383 152 118 436 176
 132 544 184 274 240 229 158 415 296 172 496 160 248 220 178 147 107 286
 190 102 214 164 186 230 104 282 145 200 322 228 191 256 251 195 113 815]


In [ ]:
df.shape

(568454, 10)

In [ ]:
df.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [ ]:
df = df.drop(columns=['Id','UserId','ProfileName'],axis=1)

In [ ]:
df.isnull().sum()

ProductId                  0
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.duplicated().sum()

282

In [ ]:
df=df.drop_duplicates()

#Feature Eng

In [ ]:
df['Review'] = df['Summary'] + ' ' + df['Text']

In [ ]:
df = df.drop(columns=['Text','Summary'],axis=1)
df.head()

ProductId  HelpfulnessNumerator  HelpfulnessDenominator  Score  \
0  B001E4KFG0                     1                       1      5   
1  B00813GRG4                     0                       0      1   
2  B000LQOCH0                     1                       1      4   
3  B000UA0QIQ                     3                       3      2   
4  B006K2ZZ7K                     0                       0      5   

         Time                                             Review  
0  1303862400  Good Quality Dog Food I have bought several of...  
1  1346976000  Not as Advertised Product arrived labeled as J...  
2  1219017600  "Delight" says it all This is a confection tha...  
3  1307923200  Cough Medicine If you are looking for the secr...  
4  1350777600  Great taffy Great taffy at a great price.  The...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 568145 entries, 0 to 568453
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype 
---  ------                  --------------   ----- 
 0   ProductId               568145 non-null  object
 1   HelpfulnessNumerator    568145 non-null  int64 
 2   HelpfulnessDenominator  568145 non-null  int64 
 3   Score                   568145 non-null  int64 
 4   Time                    568145 non-null  int64 
 5   Review                  568145 non-null  object
dtypes: int64(4), object(2)
memory usage: 30.3+ MB


In [ ]:
df['Helpness_Score']=np.where(df['HelpfulnessDenominator']>0,df['HelpfulnessNumerator']/df['HelpfulnessDenominator'],-1)
df.head(20)

ProductId  HelpfulnessNumerator  HelpfulnessDenominator  Score  \
0   B001E4KFG0                     1                       1      5   
1   B00813GRG4                     0                       0      1   
2   B000LQOCH0                     1                       1      4   
3   B000UA0QIQ                     3                       3      2   
4   B006K2ZZ7K                     0                       0      5   
5   B006K2ZZ7K                     0                       0      4   
6   B006K2ZZ7K                     0                       0      5   
7   B006K2ZZ7K                     0                       0      5   
8   B000E7L2R4                     1                       1      5   
9   B00171APVA                     0                       0      5   
10  B0001PB9FE                     1                       1      5   
11  B0009XLVG0                     4                       4      5   
12  B0009XLVG0                     1                       1      1   
13  B001GVISJM                     2                       2      4   
14  B001GVISJM                     4                       5      5   
15  B001GVISJM                     4                       5      5   
16  B001GVISJM                     0                       0      2   
17  B001GVISJM                     0                       0      5   
18  B001GVISJM                     0                       0      5   
19  B001GVISJM                     0                       0      5   

          Time                                             Review  \
0   1303862400  Good Quality Dog Food I have bought several of...   
1   1346976000  Not as Advertised Product arrived labeled as J...   
2   1219017600  "Delight" says it all This is a confection tha...   
3   1307923200  Cough Medicine If you are looking for the secr...   
4   1350777600  Great taffy Great taffy at a great price.  The...   
5   1342051200  Nice Taffy I got a wild hair for taffy and ord...   
6   1340150400  Great!  Just as good as the expensive brands! ...   
7   1336003200  Wonderful, tasty taffy This taffy is so good. ...   
8   1322006400  Yay Barley Right now I'm mostly just sprouting...   
9   1351209600  Healthy Dog Food This is a very healthy dog fo...   
10  1107820800  The Best Hot Sauce in the World I don't know i...   
11  1282867200  My cats LOVE this "diet" food better than thei...   
12  1339545600  My Cats Are Not Fans of the New Food My cats h...   
13  1288915200  fresh and greasy! good flavor! these came secu...   
14  1268352000  Strawberry Twizzlers - Yummy The Strawberry Tw...   
15  1262044800  Lots of twizzlers, just what you expect. My da...   
16  1348099200  poor taste I love eating them and they are goo...   
17  1345075200  Love it! I am very satisfied with my Twizzler ...   
18  1324598400  GREAT SWEET CANDY! Twizzlers, Strawberry my ch...   
19  1318032000  Home delivered twizlers Candy was delivered ve...   

    Helpness_Score  
0              1.0  
1             -1.0  
2              1.0  
3              1.0  
4             -1.0  
5             -1.0  
6             -1.0  
7             -1.0  
8              1.0  
9             -1.0  
10             1.0  
11             1.0  
12             1.0  
13             1.0  
14             0.8  
15             0.8  
16            -1.0  
17            -1.0  
18            -1.0  
19            -1.0

In [ ]:
df.drop(['HelpfulnessDenominator','HelpfulnessNumerator'],axis=1,inplace=True)
df.head()

ProductId  Score        Time  \
0  B001E4KFG0      5  1303862400   
1  B00813GRG4      1  1346976000   
2  B000LQOCH0      4  1219017600   
3  B000UA0QIQ      2  1307923200   
4  B006K2ZZ7K      5  1350777600   

                                              Review  Helpness_Score  
0  Good Quality Dog Food I have bought several of...             1.0  
1  Not as Advertised Product arrived labeled as J...            -1.0  
2  "Delight" says it all This is a confection tha...             1.0  
3  Cough Medicine If you are looking for the secr...             1.0  
4  Great taffy Great taffy at a great price.  The...            -1.0

In [ ]:
from datetime import datetime
df['Time_ymd']=df['Time'].apply(lambda col: datetime.utcfromtimestamp(int(col)).strftime('%Y-%m-%d'))

df.drop(['Time'] ,axis=1, inplace=True)
df.head()

ProductId  Score                                             Review  \
0  B001E4KFG0      5  Good Quality Dog Food I have bought several of...   
1  B00813GRG4      1  Not as Advertised Product arrived labeled as J...   
2  B000LQOCH0      4  "Delight" says it all This is a confection tha...   
3  B000UA0QIQ      2  Cough Medicine If you are looking for the secr...   
4  B006K2ZZ7K      5  Great taffy Great taffy at a great price.  The...   

   Helpness_Score    Time_ymd  
0             1.0  2011-04-27  
1            -1.0  2012-09-07  
2             1.0  2008-08-18  
3             1.0  2011-06-13  
4            -1.0  2012-10-21

#Text Preprocessing

#Case Folding , stopwords , punctuation

In [ ]:
punctuation =  set(string.punctuation)
stop_words = set(stopwords.words("english"))
stop_words.update(["br", "href","amazon","product","counter"])

In [ ]:

def Clean_Text(review):
  x = review
  x = re.sub(r'https?:\S', '', x)
  x = re.sub(r'{link}', '', x)
  x = re.sub(r'@[\w]', '', x)
  x = re.sub(r'[^A-Za-z0-9]+', ' ', x)
  x = re.sub(r'\b[0-9]+\b', '', x)
  x = re.sub(r'&[a-z]+', '', x)
  x = ''.join(w for w in x if w not in punctuation)
  x = x.replace('[^a-zA-Z#]',' ')

  x = [w.lower() for w in x.split() if w.lower() not in stop_words]
  x = [w for w in x if len(w) > 3]
  return x

In [ ]:
df['Clean_Text'] = df['Review'].apply(lambda x: Clean_Text(x) if isinstance(x, str) else '')

In [ ]:
df.head(20)

ProductId  Score                                             Review  \
0   B001E4KFG0      5  Good Quality Dog Food I have bought several of...   
1   B00813GRG4      1  Not as Advertised Product arrived labeled as J...   
2   B000LQOCH0      4  "Delight" says it all This is a confection tha...   
3   B000UA0QIQ      2  Cough Medicine If you are looking for the secr...   
4   B006K2ZZ7K      5  Great taffy Great taffy at a great price.  The...   
5   B006K2ZZ7K      4  Nice Taffy I got a wild hair for taffy and ord...   
6   B006K2ZZ7K      5  Great!  Just as good as the expensive brands! ...   
7   B006K2ZZ7K      5  Wonderful, tasty taffy This taffy is so good. ...   
8   B000E7L2R4      5  Yay Barley Right now I'm mostly just sprouting...   
9   B00171APVA      5  Healthy Dog Food This is a very healthy dog fo...   
10  B0001PB9FE      5  The Best Hot Sauce in the World I don't know i...   
11  B0009XLVG0      5  My cats LOVE this "diet" food better than thei...   
12  B0009XLVG0      1  My Cats Are Not Fans of the New Food My cats h...   
13  B001GVISJM      4  fresh and greasy! good flavor! these came secu...   
14  B001GVISJM      5  Strawberry Twizzlers - Yummy The Strawberry Tw...   
15  B001GVISJM      5  Lots of twizzlers, just what you expect. My da...   
16  B001GVISJM      2  poor taste I love eating them and they are goo...   
17  B001GVISJM      5  Love it! I am very satisfied with my Twizzler ...   
18  B001GVISJM      5  GREAT SWEET CANDY! Twizzlers, Strawberry my ch...   
19  B001GVISJM      5  Home delivered twizlers Candy was delivered ve...   

    Helpness_Score    Time_ymd  \
0              1.0  2011-04-27   
1             -1.0  2012-09-07   
2              1.0  2008-08-18   
3              1.0  2011-06-13   
4             -1.0  2012-10-21   
5             -1.0  2012-07-12   
6             -1.0  2012-06-20   
7             -1.0  2012-05-03   
8              1.0  2011-11-23   
9             -1.0  2012-10-26   
10             1.0  2005-02-08   
11             1.0  2010-08-27   
12             1.0  2012-06-13   
13             1.0  2010-11-05   
14             0.8  2010-03-12   
15             0.8  2009-12-29   
16            -1.0  2012-09-20   
17            -1.0  2012-08-16   
18            -1.0  2011-12-23   
19            -1.0  2011-10-08   

                                           Clean_Text  
0   [good, quality, food, bought, several, vitalit...  
1   [advertised, arrived, labeled, jumbo, salted, ...  
2   [delight, says, confection, around, centuries,...  
3   [cough, medicine, looking, secret, ingredient,...  
4   [great, taffy, great, taffy, great, price, wid...  
5   [nice, taffy, wild, hair, taffy, ordered, five...  
6   [great, good, expensive, brands, saltwater, ta...  
7   [wonderful, tasty, taffy, taffy, good, soft, c...  
8   [barley, right, mostly, sprouting, cats, grass...  
9   [healthy, food, healthy, food, good, digestion...  
10  [best, sauce, world, know, cactus, tequila, un...  
11  [cats, love, diet, food, better, regular, food...  
12  [cats, fans, food, cats, happily, eating, feli...  
13  [fresh, greasy, good, flavor, came, securely, ...  
14  [strawberry, twizzlers, yummy, strawberry, twi...  
15  [lots, twizzlers, expect, daughter, loves, twi...  
16  [poor, taste, love, eating, good, watching, lo...  
17  [love, satisfied, twizzler, purchase, shared, ...  
18  [great, sweet, candy, twizzlers, strawberry, c...  
19  [home, delivered, twizlers, candy, delivered, ...

In [ ]:
# Convert lists of words into strings
df['Clean_Text'] = df['Clean_Text'].apply(lambda x: ' '.join(x))
print(df)

         ProductId  Score                                             Review  \
0       B001E4KFG0      5  Good Quality Dog Food I have bought several of...   
1       B00813GRG4      1  Not as Advertised Product arrived labeled as J...   
2       B000LQOCH0      4  "Delight" says it all This is a confection tha...   
3       B000UA0QIQ      2  Cough Medicine If you are looking for the secr...   
4       B006K2ZZ7K      5  Great taffy Great taffy at a great price.  The...   
...            ...    ...                                                ...   
568449  B001EO7N10      5  Will not do without Great for sesame chicken.....   
568450  B003S1WTCU      2  disappointed I'm disappointed with the flavor....   
568451  B004I613EE      5  Perfect for our maltipoo These stars are small...   
568452  B004I613EE      5  Favorite Training and reward treat These are t...   
568453  B001LR2CU2      5  Great Honey I am very satisfied ,product is as...   

        Helpness_Score    Time_ymd  \
0

# Part Of Speech

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
pos_tags = [nltk.pos_tag(nltk.word_tokenize(review))for review in df['Clean_Text']]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!




```
# This is formatted as code
```

# Lemmatization

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import pandas as pd

# Initialize variables and objects
lemmatizer = WordNetLemmatizer()

# A dictionary mapping part-of-speech tags to WordNet part-of-speech constants.
tag_dict = {"J": wn.ADJ,
            "N": wn.NOUN,
            "V": wn.VERB,
            "R": wn.ADV}

# Maps a part-of-speech tag (e.g., 'NN') to its WordNet equivalent.
def mapToWordEq(tag):
    return tag_dict.get(tag[0].upper(), None)

# Function to lemmatize a word given its tuple (word, pos_tag)
def lemmatize_tupla_word_postag(tupla):
    tag = mapToWordEq(tupla[1])
    return lemmatizer.lemmatize(tupla[0], tag) if tag is not None else tupla[0]

# Function to perform bag of words processing on a sentence
def bag_of_words(sentence):
    original_words = word_tokenize(sentence)
    tagged_words = nltk.pos_tag(original_words)
    lemmatized_words = [lemmatize_tupla_word_postag(ow) for ow in tagged_words]

    return lemmatized_words

In [ ]:
df.columns

Index(['ProductId', 'Score', 'Review', 'Helpness_Score', 'Time_ymd',
       'Clean_Text'],
      dtype='object')

In [ ]:

# Process each review in the DataFrame
processed_reviews = []
for index, row in df.iterrows():
    review_text = row['Clean_Text']

    cleaned_words = bag_of_words(review_text)

    # Append the cleaned words and 'Liked' value to the list
    processed_reviews.append({'Clean_Text': cleaned_words, 'ProductId': row['ProductId'], 'Score': row['Score'], 'Review': row['Review'], 'Helpness_Score': row['Helpness_Score']})

# Create a new DataFrame from the processed reviews
Review_data_Processed = pd.DataFrame(processed_reviews)

# Display the processed DataFrame
print(Review_data_Processed)

                                               Clean_Text   ProductId  Score  \
0       [good, quality, food, buy, several, vitality, ...  B001E4KFG0      5   
1       [advertise, arrive, labeled, jumbo, salt, pean...  B00813GRG4      1   
2       [delight, say, confection, around, century, li...  B000LQOCH0      4   
3       [cough, medicine, look, secret, ingredient, ro...  B000UA0QIQ      2   
4       [great, taffy, great, taffy, great, price, wid...  B006K2ZZ7K      5   
...                                                   ...         ...    ...   
568140  [without, great, sesame, chicken, good, good, ...  B001EO7N10      5   
568141  [disappoint, disappointed, flavor, chocolate, ...  B003S1WTCU      2   
568142  [perfect, maltipoo, star, small, give, train, ...  B004I613EE      5   
568143  [favorite, train, reward, treat, best, treat, ...  B004I613EE      5   
568144  [great, honey, satisfy, advertised, cereal, vi...  B001LR2CU2      5   

                                       

In [ ]:
df.dropna(inplace=True)
print(df.isnull().sum())

ProductId         0
Score             0
Review            0
Helpness_Score    0
Time_ymd          0
Clean_Text        0
dtype: int64
ProductId         0
Score             0
Review            0
Helpness_Score    0
Time_ymd          0
Clean_Text        0
dtype: int64


In [ ]:
df

ProductId  Score                                             Review  \
0       B001E4KFG0      5  Good Quality Dog Food I have bought several of...   
1       B00813GRG4      1  Not as Advertised Product arrived labeled as J...   
2       B000LQOCH0      4  "Delight" says it all This is a confection tha...   
3       B000UA0QIQ      2  Cough Medicine If you are looking for the secr...   
4       B006K2ZZ7K      5  Great taffy Great taffy at a great price.  The...   
...            ...    ...                                                ...   
568449  B001EO7N10      5  Will not do without Great for sesame chicken.....   
568450  B003S1WTCU      2  disappointed I'm disappointed with the flavor....   
568451  B004I613EE      5  Perfect for our maltipoo These stars are small...   
568452  B004I613EE      5  Favorite Training and reward treat These are t...   
568453  B001LR2CU2      5  Great Honey I am very satisfied ,product is as...   

        Helpness_Score    Time_ymd  \
0                  1.0  2011-04-27   
1                 -1.0  2012-09-07   
2                  1.0  2008-08-18   
3                  1.0  2011-06-13   
4                 -1.0  2012-10-21   
...                ...         ...   
568449            -1.0  2011-03-09   
568450            -1.0  2012-03-09   
568451             1.0  2012-02-21   
568452             1.0  2012-03-13   
568453            -1.0  2012-05-31   

                                               Clean_Text  
0       good quality food bought several vitality cann...  
1       advertised arrived labeled jumbo salted peanut...  
2       delight says confection around centuries light...  
3       cough medicine looking secret ingredient robit...  
4       great taffy great taffy great price wide assor...  
...                                                   ...  
568449  without great sesame chicken good better restu...  
568450  disappointed disappointed flavor chocolate not...  
568451  perfect maltipoo stars small give training ses...  
568452  favorite training reward treat best treats tra...  
568453  great honey satisfied advertised cereal vinega...  

[568145 rows x 6 columns]

In [ ]:
def score_classification(score):
    if score > 3:
        return 2
    elif score == 3:
        return 1
    else:
        return 0

In [ ]:
df['SentimentManiual']=df['Score'].apply(lambda x:score_classification(x))
df.head()

ProductId  Score                                             Review  \
0  B001E4KFG0      5  Good Quality Dog Food I have bought several of...   
1  B00813GRG4      1  Not as Advertised Product arrived labeled as J...   
2  B000LQOCH0      4  "Delight" says it all This is a confection tha...   
3  B000UA0QIQ      2  Cough Medicine If you are looking for the secr...   
4  B006K2ZZ7K      5  Great taffy Great taffy at a great price.  The...   

   Helpness_Score    Time_ymd  \
0             1.0  2011-04-27   
1            -1.0  2012-09-07   
2             1.0  2008-08-18   
3             1.0  2011-06-13   
4            -1.0  2012-10-21   

                                          Clean_Text  SentimentManiual  
0  good quality food bought several vitality cann...                 2  
1  advertised arrived labeled jumbo salted peanut...                 0  
2  delight says confection around centuries light...                 2  
3  cough medicine looking secret ingredient robit...                 0  
4  great taffy great taffy great price wide assor...                 2

In [ ]:
df['SentimentManiual'].value_counts()

2    443562
0     81971
1     42612
Name: SentimentManiual, dtype: int64

In [ ]:
df.shape

(568145, 7)

#Sentiment Analysis


In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


True

In [ ]:
analyzer = SentimentIntensityAnalyzer()

def get_sentiment(text):
    scores = analyzer.polarity_scores(text)

    if scores['compound'] >= 0.05 :
        sentiment = 2
    elif scores['compound'] <= -0.05:
        sentiment = 0
    else:
        sentiment = 1

    return sentiment


df['sentimentPolarity'] = df['Clean_Text'].apply(get_sentiment)

df

ProductId  Score                                             Review  \
0       B001E4KFG0      5  Good Quality Dog Food I have bought several of...   
1       B00813GRG4      1  Not as Advertised Product arrived labeled as J...   
2       B000LQOCH0      4  "Delight" says it all This is a confection tha...   
3       B000UA0QIQ      2  Cough Medicine If you are looking for the secr...   
4       B006K2ZZ7K      5  Great taffy Great taffy at a great price.  The...   
...            ...    ...                                                ...   
568449  B001EO7N10      5  Will not do without Great for sesame chicken.....   
568450  B003S1WTCU      2  disappointed I'm disappointed with the flavor....   
568451  B004I613EE      5  Perfect for our maltipoo These stars are small...   
568452  B004I613EE      5  Favorite Training and reward treat These are t...   
568453  B001LR2CU2      5  Great Honey I am very satisfied ,product is as...   

        Helpness_Score    Time_ymd  \
0                  1.0  2011-04-27   
1                 -1.0  2012-09-07   
2                  1.0  2008-08-18   
3                  1.0  2011-06-13   
4                 -1.0  2012-10-21   
...                ...         ...   
568449            -1.0  2011-03-09   
568450            -1.0  2012-03-09   
568451             1.0  2012-02-21   
568452             1.0  2012-03-13   
568453            -1.0  2012-05-31   

                                               Clean_Text  SentimentManiual  \
0       good quality food bought several vitality cann...                 2   
1       advertised arrived labeled jumbo salted peanut...                 0   
2       delight says confection around centuries light...                 2   
3       cough medicine looking secret ingredient robit...                 0   
4       great taffy great taffy great price wide assor...                 2   
...                                                   ...               ...   
568449  without great sesame chicken good better restu...                 2   
568450  disappointed disappointed flavor chocolate not...                 0   
568451  perfect maltipoo stars small give training ses...                 2   
568452  favorite training reward treat best treats tra...                 2   
568453  great honey satisfied advertised cereal vinega...                 2   

        sentimentScore  sentimentPolarity  
0                    5                  2  
1                    2                  0  
2                    5                  2  
3                    4                  2  
4                    5                  2  
...                ...                ...  
568449               5                  2  
568450               1                  0  
568451               5                  2  
568452               5                  2  
568453               5                  2  

[568145 rows x 9 columns]

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(df['SentimentManiual'], df['sentimentPolarity']))

[[ 24158   3845  53968]
 [  3490   1219  37903]
 [  7610   3333 432619]]


In [ ]:
from sklearn.metrics import classification_report, accuracy_score

accuracy = accuracy_score(df['SentimentManiual'], df['sentimentPolarity'])

print("Accuracy:", accuracy)

print(classification_report(df['SentimentManiual'], df['sentimentPolarity']))

Accuracy: 0.80612519691276
              precision    recall  f1-score   support

           0       0.69      0.29      0.41     81971
           1       0.15      0.03      0.05     42612
           2       0.82      0.98      0.89    443562

    accuracy                           0.81    568145
   macro avg       0.55      0.43      0.45    568145
weighted avg       0.75      0.81      0.76    568145



In [ ]:
def eqNeg (cmp):
  return (cmp-(-1))*((2-1)/(-0.05+1))+1

def eqPos(cmp):
  return (cmp-(0.05))*((5-4)/(1-(0.05)))+4


In [ ]:
analyzer = SentimentIntensityAnalyzer()

def get_sentiment(text):
    scores = analyzer.polarity_scores(text)

    if scores['compound'] >= 0.05 :
        sentiment = round(eqPos(scores['compound']))
    elif scores['compound'] <= -0.05:
        sentiment = round(eqNeg(scores['compound']))
    else:
        sentiment = 3

    return sentiment

df['scores']= df['Clean_Text'].apply(analyzer.polarity_scores)

df['sentiment'] = df['Clean_Text'].apply(get_sentiment)

df

ProductId  Score                                             Review  \
0       B001E4KFG0      5  Good Quality Dog Food I have bought several of...   
1       B00813GRG4      1  Not as Advertised Product arrived labeled as J...   
2       B000LQOCH0      4  "Delight" says it all This is a confection tha...   
3       B000UA0QIQ      2  Cough Medicine If you are looking for the secr...   
4       B006K2ZZ7K      5  Great taffy Great taffy at a great price.  The...   
...            ...    ...                                                ...   
568449  B001EO7N10      5  Will not do without Great for sesame chicken.....   
568450  B003S1WTCU      2  disappointed I'm disappointed with the flavor....   
568451  B004I613EE      5  Perfect for our maltipoo These stars are small...   
568452  B004I613EE      5  Favorite Training and reward treat These are t...   
568453  B001LR2CU2      5  Great Honey I am very satisfied ,product is as...   

        Helpness_Score    Time_ymd  \
0                  1.0  2011-04-27   
1                 -1.0  2012-09-07   
2                  1.0  2008-08-18   
3                  1.0  2011-06-13   
4                 -1.0  2012-10-21   
...                ...         ...   
568449            -1.0  2011-03-09   
568450            -1.0  2012-03-09   
568451             1.0  2012-02-21   
568452             1.0  2012-03-13   
568453            -1.0  2012-05-31   

                                               Clean_Text  SentimentManiual  \
0       good quality food bought several vitality cann...                 2   
1       advertised arrived labeled jumbo salted peanut...                 0   
2       delight says confection around centuries light...                 2   
3       cough medicine looking secret ingredient robit...                 0   
4       great taffy great taffy great price wide assor...                 2   
...                                                   ...               ...   
568449  without great sesame chicken good better restu...                 2   
568450  disappointed disappointed flavor chocolate not...                 0   
568451  perfect maltipoo stars small give training ses...                 2   
568452  favorite training reward treat best treats tra...                 2   
568453  great honey satisfied advertised cereal vinega...                 2   

                                                   scores  sentiment  
0       {'neg': 0.0, 'neu': 0.448, 'pos': 0.552, 'comp...          5  
1       {'neg': 0.135, 'neu': 0.75, 'pos': 0.115, 'com...          2  
2       {'neg': 0.126, 'neu': 0.535, 'pos': 0.339, 'co...          5  
3       {'neg': 0.0, 'neu': 0.861, 'pos': 0.139, 'comp...          4  
4       {'neg': 0.0, 'neu': 0.339, 'pos': 0.661, 'comp...          5  
...                                                   ...        ...  
568449  {'neg': 0.157, 'neu': 0.381, 'pos': 0.462, 'co...          5  
568450  {'neg': 0.389, 'neu': 0.455, 'pos': 0.156, 'co...          1  
568451  {'neg': 0.0, 'neu': 0.714, 'pos': 0.286, 'comp...          5  
568452  {'neg': 0.05, 'neu': 0.206, 'pos': 0.744, 'com...          5  
568453  {'neg': 0.0, 'neu': 0.465, 'pos': 0.535, 'comp...          5  

[568145 rows x 9 columns]

In [ ]:
df.rename(columns={'sentiment': 'sentimentScore'}, inplace=True)
df = df.drop(columns=['scores'],axis=1)

In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(df['Score'], df['sentimentScore']))

[[ 10938   7978   2642   9238  21435]
 [  2364   2878   1203   4692  18603]
 [  1241   2249   1219   5034  32869]
 [   715   1295    824   4523  73270]
 [  1821   3779   2509  13655 341171]]


In [ ]:
from sklearn.metrics import classification_report, accuracy_score
accuracy = accuracy_score(df['Score'], df['sentimentScore'])
print("Accuracy:", accuracy)

print(classification_report(df['Score'], df['sentimentScore']))

Accuracy: 0.634924183087064
              precision    recall  f1-score   support

           1       0.64      0.21      0.32     52231
           2       0.16      0.10      0.12     29740
           3       0.15      0.03      0.05     42612
           4       0.12      0.06      0.08     80627
           5       0.70      0.94      0.80    362935

    accuracy                           0.63    568145
   macro avg       0.35      0.27      0.27    568145
weighted avg       0.54      0.63      0.56    568145



In [ ]:
final=df
final

ProductId  Score                                             Review  \
0       B001E4KFG0      5  Good Quality Dog Food I have bought several of...   
1       B00813GRG4      1  Not as Advertised Product arrived labeled as J...   
2       B000LQOCH0      4  "Delight" says it all This is a confection tha...   
3       B000UA0QIQ      2  Cough Medicine If you are looking for the secr...   
4       B006K2ZZ7K      5  Great taffy Great taffy at a great price.  The...   
...            ...    ...                                                ...   
568449  B001EO7N10      5  Will not do without Great for sesame chicken.....   
568450  B003S1WTCU      2  disappointed I'm disappointed with the flavor....   
568451  B004I613EE      5  Perfect for our maltipoo These stars are small...   
568452  B004I613EE      5  Favorite Training and reward treat These are t...   
568453  B001LR2CU2      5  Great Honey I am very satisfied ,product is as...   

        Helpness_Score    Time_ymd  \
0                  1.0  2011-04-27   
1                 -1.0  2012-09-07   
2                  1.0  2008-08-18   
3                  1.0  2011-06-13   
4                 -1.0  2012-10-21   
...                ...         ...   
568449            -1.0  2011-03-09   
568450            -1.0  2012-03-09   
568451             1.0  2012-02-21   
568452             1.0  2012-03-13   
568453            -1.0  2012-05-31   

                                               Clean_Text  SentimentManiual  \
0       good quality food bought several vitality cann...                 2   
1       advertised arrived labeled jumbo salted peanut...                 0   
2       delight says confection around centuries light...                 2   
3       cough medicine looking secret ingredient robit...                 0   
4       great taffy great taffy great price wide assor...                 2   
...                                                   ...               ...   
568449  without great sesame chicken good better restu...                 2   
568450  disappointed disappointed flavor chocolate not...                 0   
568451  perfect maltipoo stars small give training ses...                 2   
568452  favorite training reward treat best treats tra...                 2   
568453  great honey satisfied advertised cereal vinega...                 2   

                                                   scores  sentiment  
0       {'neg': 0.0, 'neu': 0.448, 'pos': 0.552, 'comp...          5  
1       {'neg': 0.135, 'neu': 0.75, 'pos': 0.115, 'com...          2  
2       {'neg': 0.126, 'neu': 0.535, 'pos': 0.339, 'co...          5  
3       {'neg': 0.0, 'neu': 0.861, 'pos': 0.139, 'comp...          4  
4       {'neg': 0.0, 'neu': 0.339, 'pos': 0.661, 'comp...          5  
...                                                   ...        ...  
568449  {'neg': 0.157, 'neu': 0.381, 'pos': 0.462, 'co...          5  
568450  {'neg': 0.389, 'neu': 0.455, 'pos': 0.156, 'co...          1  
568451  {'neg': 0.0, 'neu': 0.714, 'pos': 0.286, 'comp...          5  
568452  {'neg': 0.05, 'neu': 0.206, 'pos': 0.744, 'com...          5  
568453  {'neg': 0.0, 'neu': 0.465, 'pos': 0.535, 'comp...          5  

[568145 rows x 9 columns]

In [ ]:
final.to_csv("Cleaned_Data.csv")